---
  - hosts: secretsvid
    vars_files:
      - '../vars/vault.yaml'
    roles:
      - role: grog.package
      - role: geerlingguy.docker
      - role: ironicbadger.bash_aliases
      - role: ironicbadger.docker_compose_generator
        tags: compose
